In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
a = np.arange(5)
a+20

array([20, 21, 22, 23, 24])

In [3]:
a + 0

array([0, 1, 2, 3, 4])

In [4]:
a = np.arange(5)
print(a <=3)

[ True  True  True  True False]


In [5]:
array_list = [1,2,3,4,5]
array_numpy = np.array(array_list)

print(array_list.__sizeof__())
print(array_numpy.__sizeof__())



80
116


In [6]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64


In [7]:
s = pd.Series([np.nan, 1, 2, np.nan, 3])
s = s.fillna(method='ffill')

print(s)

0    NaN
1    1.0
2    2.0
3    2.0
4    3.0
dtype: float64


In [8]:
arr = np.array([1,2,3,4,5,5,3,8,9,4])

In [12]:
a = np.array(([1,2,3,4,5],[6,7,8,9,10]))
b = np.max(a, axis=1).sum()
print(b)

15


In [13]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
a = np.ones((2,4))
b = a.reshape((4,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
filedata = np.genfromtxt('data.txt', delimiter=',')
output = filedata[filedata < 50]
print(output)

[29. 32. 45. 15.  5. 22.]


In [21]:
def mean(arr):
    return np.sum(arr)/len(arr)

In [22]:
arr = [1,2,3,4,5,6,7,8,9,10]
mean(arr)

5.5

In [23]:
def variance(arr):
    mean_x = mean(arr)
    return np.sum([(arr_i - mean_x)**2 for arr_i in arr]) / len(arr)

In [24]:
variance(arr)

8.25

In [25]:
np.nanvar(arr)

8.25

In [26]:
def SD(arr):
    return np.sqrt(variance(arr))

In [28]:
SD(arr)

2.8722813232690143

In [30]:
np.sqrt(np.var(arr))

2.8722813232690143